version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: routine
      POSTGRES_PASSWORD: routine123
      POSTGRES_DB: routine-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    container_name: minio_routine
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9090"
    ports:
      - "9001:9000"
      - "9091:9090"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc:latest
    container_name: minio_routine_init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c '
      ATTEMPTS=0;
      until mc --insecure alias set local http://minio:9000 minioadmin minioadmin; do
        ATTEMPTS=`expr $ATTEMPTS + 1`;
        echo "waiting for minio... attempt $ATTEMPTS";
        if [ "$ATTEMPTS" -ge 30 ]; then
          echo "minio not ready, exiting" && exit 1;
        fi;
        sleep 2;
      done;
      mc --insecure mb --ignore-existing local/virtual-cards;
      mc anonymous --insecure set public local/virtual-cards || true;
      '
    restart: "no"
volumes:
  postgres_data:
  minio_data:
